// MOVIE
export const FETCH_POPULAR_MOVIE = 'FETCH_POPULAR_MOVIE';
export const FETCH_TRENDING_MOVIE = 'FETCH_TRENDING_MOVIE';
export const FETCH_TOP_RATED = 'FETCH_TOP_RATED';

// TV
export const FETCH_POPULAR_TV = 'FETCH_POPULAR_TV';
export const FETCH_TRENDING_TV = 'FETCH_TRENDING_TV';
