// SEARCH
export const FETCH_SEARCH_VALUE = 'FETCH_SEARCH_VALUE';

// MOVIE
export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_POPULAR_MOVIE = 'FETCH_POPULAR_MOVIE';
export const FETCH_TRENDING_MOVIE = 'FETCH_TRENDING_MOVIE';
export const FETCH_TOP_RATED_MOVIE = 'FETCH_TOP_RATED_MOVIE';
export const FETCH_UPCOMING_MOVIE = 'FETCH_UPCOMING_MOVIE';
export const FETCH_NOW_PLAYING_MOVIE = 'FETCH_NOW_PLAYING_MOVIE';

// TV
export const FETCH_TV_DETAILS = 'FETCH_TV_DETAILS';
export const FETCH_POPULAR_TV = 'FETCH_POPULAR_TV';
export const FETCH_TRENDING_TV = 'FETCH_TRENDING_TV';
export const FETCH_AIRING_TODAY__TV = 'FETCH_AIRING_TODAY__TV';
export const FETCH_ON_THE_AIR__TV = 'FETCH_ON_THE_AIR__TV';
export const FETCH_TOP_RATED_TV = 'FETCH_TOP_RATED_TV';
